### ISSUE TITLE
Duplicating Entites on top of chest

### ISSUE THREAD

**Issue by kzaqul** [EpicEricEE/ShopChest#11]
Every time i visit a shop someone has created, the floating item icon on top will duplicate. Occasionally
![screen shot 2016-07-12 at 12 56 23 pm](https://cloud.githubusercontent.com/assets/13631752/16777681/1a8b92ee-4830-11e6-8d3e-1a002ebd4103.png)
![screen shot 2016-07-12 at 12 56 29 pm](https://cloud.githubusercontent.com/assets/13631752/16777682/1afaf864-4830-11e6-9655-eb765a020a36.png)

 you can pick up the duplicated items as well

**Comment by EpicEricEE** [comment]
Does the item only duplicate when you are walking past its shop?

**Comment by kzaqul** [comment]
Hmm, I Wouldn't Say So, Cause It Doesn't Do It To Every Chest That Has A Shop Assigned To It.

I Have Towny, So The Shops Are On A Single Chunk. When Ever I Walk To The Shop Town Some Stores Will Have It and Some Will Not.

**Comment by EpicEricEE** [comment]
Okay, I think the issue is not caused by Towny. You can download a version that displays quite a bit information _(about every item reloaded)_ in the console when you reload the shops [here](https://drive.google.com/open?id=0BxqKmdgOnShjeVhYaXJNMzlxTWc). It may be helpful, if there aren't too many shops, but it should also be okay if there are. Please send me the complete log found in _/logs/latest.log_. I hope this can help fixing the issue, as I don't face it.
