### ISSUE TITLE
ShopChest  with lockette Fail

### ISSUE THREAD

**Issue by Extremediver** [EpicEricEE/ShopChest#15]
Server 1.10.2 Spigot / Bungee
Lockette - UUID supported!! 1.8.36
ShopChest 1.9.1
A locket Chest with Lockette Private lock. on a plot which is not locked where anyone can build. And another player make a shop with / shop create <AMOUNT> <buy-price> <sell-price> [normal]. If you hit the locked Chest. So, one can empty a chest. And no one can go in the Chest as it is locked by two different players

**Comment by EpicEricEE** [comment]
If you don't have a permission plugin installed, everyone has permission to create a shop on a protected chest!
If I understood your issue wrongly, please tell me.

I tried the following _(with the next version of ShopChest)_:
- Create a shop on a not protected chest and let another player create a protection
  - Created the shop > OK
  - Created a protection sign with another player > OK
  - Open/Click the chest with player who created the protection _(should not work)_ > FAILED

- Create a protected chest and let another player create a shop on top of it
  - Protect the chest > OK
  - Create a shop on top of the locked chest with another player _(should not work)_> FAILED _(would need permission "shopchest.create.protected" to work)_

Lockette support will be fixed in the next version _(I didn't try it in the current version, so I don't know if it even was broken)_

_(If it was broken, it was probably fixed in 76ea273)_
