### ISSUE TITLE
Shops staying after "AreaShop" reset.

### ISSUE THREAD

**Issue by Nomiis** [EpicEricEE/ShopChest#151]
Hi there!
I have been using your plugin for a good while, and we decided to add a "Black Market" to our prison server, and we are using your plugin for the shops there (run by players). The problem is, that the "shop" stays there after a "Market" spot is reset, if the rent is not paid, or if it's unrented. The chest is removed, but the "shop" itself stays. I looked in the config of your plugin and found this: "remove-shop-on-error: flase" and set that to "remove-shop-on-error: true", but it did nothing :/ - Do you perhaps know how to fix this? The market place renting is run by AreaShop - And i don't see any errors in console on startup but i do see this error when the plugin is reloaded (via /shop reload): https://pastebin.com/raw/grJBMtvi

The only ways (currently) to get rid of the shops are by placing a chest underneath the Shop and then doing /shop remove, or by doing /shop reload manually which gives an error plus is quite annoying for our players to do every time they take over a new market spot.

**Comment by tomtehtom** [comment]
Having the same issue there is "Areashop integration" which does not work and it meant to hook into areashop so that when a region is unrented/expires ShopChest will hook into that events and clear the shops in the region. This however doesn't work. I have in some cases got /shop reload to trigger when areashop unrents/expires and this removes the hologram as it detects there is no chest but even the "Remove shop on error" doesn't work as placing a chest back in the spot revives the shop and puts the hologram back. This needs fixing as anyone using Areashop/Shopchest cannot fully automate the process as shops needs removing manually. A server restart fixes this issue and removes the shops but a reload, the areashop integration in ShopChest and the remove on error do not work/fix this issue.

**Comment by EpicEricEE** [comment]
Should be fixed with cf4d171
