### ISSUE TITLE
Hologram issue

### ISSUE THREAD

**Issue by KlenerTeufel96** [EpicEricEE/ShopChest#155]
Everytime i create a Shop there is  an R for Buy an Sell, i dont know why.. Can you help me pls?
![shopchest issue](https://user-images.githubusercontent.com/26856657/31353440-e3ea4fdc-ad32-11e7-940b-a59538a8e0cc.png)

**Comment by sigmaroot** [comment]
What version do you use?

**Comment by KlenerTeufel96** [comment]
Server is on 1.8.8 Spigot and i use the newest version 1.12.3 of ShopChest

**Comment by EpicEricEE** [comment]
Maybe it's a typo in the hologram format or in the economy plugin's currency format.

**Comment by KlenerTeufel96** [comment]
Yes, in the Vault Hook was an issue ... Now i program my own EcoSys and i get new Errors :D 
Maybe you can help me again ^^

Here´s the Debug.txt, the Console Error and the Hook Code which is written in the console error but i dont see the issue, maybe i´m blind xD Sorry for my bad english ._. 

[debug.txt](https://github.com/EpicEricEE/ShopChest/files/1443552/debug.txt)

![shopchest error](https://user-images.githubusercontent.com/26856657/32409182-37ee9c54-c1a7-11e7-82de-e7124131885c.png)

![hook code 150](https://user-images.githubusercontent.com/26856657/32409184-3b56be8a-c1a7-11e7-84cd-db0b12ad221d.png)

**Comment by sigmaroot** [comment]
Some possibilities:

1.) getManager() does return null
2.) getConfig() does return null because there is no config file loaded
3.) getString doesn't return a value because there is no "Currency Format" (shouldn't it be currency-format or something like that in yaml?)
4.) arg0 is passed as null, therefore a NPE occurs

Try to separate line 150 into some lines so you can see where the NPE occurs.

BTW: This is no error by ShopChest, it is caused by your own Plugin vault_hook.
I bet you are not an experianced programer? Try to find out what the NPE causes to fix it 😄

**Comment by KlenerTeufel96** [comment]
Uhh yes, arg0 was the problem, so i turn it to amount and it works :)

Thank all for your help 👍
