### ISSUE TITLE
Double item

### ISSUE THREAD

**Issue by NTCNeD** [EpicEricEE/ShopChest#2]
sometimes, the items floating above the chests multiply:

http://postimg.org/image/bbpd6qpwh/

Any fix ?

**Comment by EpicEricEE** [comment]
I know that bug, I had it myself on my test server but I haven't found a fix for it yet and as this bug is very rarely, I don't know when it occurs. The only way to remove the items on top of the chest is putting lava on top of the chest and take it back very fast so the items are removed but the lava hasn't spread yet. After that you must reload the shops (/shop reload). 

*If anyone finds an issue in the code, please let me know.*
