### ISSUE TITLE
AllowDecimal:

### ISSUE THREAD

**Issue by Creatif** [EpicEricEE/ShopChest#20]
Hello,

it's me again !
Thanks for saveinlog !

Another request:
`- AllowDecimal: true/false`

On my server, I use essentiels with # ##0 format (no decimal), and I don't want my user use decimal in there shop.
Do you think you could add an error when a player try /shop create 20 15.58 20.1 like:

```
# Define a message when a player try to user decimal:
message.shopinfo-decimal=&cYou must use integer nomber to sell items.
```

Thanks again,
Crea

**Comment by EpicEricEE** [comment]
I'll add this, but then your server won't support the _auto-calculate-item-amount_ feature, because the calculated price would probably contain decimals. I'll make it so, that the _auto-calculate-item-amount_ configuration value will be automatically set to _false_ when disabling _allow-decimals-in-price_.

**Comment by Creatif** [comment]
perfect !
I stay tuned for the next update :))).
