### ISSUE TITLE
/shop reload is very laggy

### ISSUE THREAD

**Issue by ken-kentan** [EpicEricEE/ShopChest#201]
[ShopUtils.reloadShops()](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/utils/ShopUtils.java#L228) is very slow and occupy the server main thread.
It takes about 20 sec. (1500 shops).
So, All players will time out.

I debugged [this method](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/utils/ShopUtils.java#L228).
I think [Shop.createHologram()](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/shop/Shop.java#L161) is late due to it.

debug log
> [30/07/2018 09:56:00.742] Creating shop (#8400)
[30/07/2018 09:56:00.742] Creating hologram (#8400)
[30/07/2018 09:56:00.755] Creating item (#8400)
[30/07/2018 09:56:00.755] Adding shop... (#8400)
[30/07/2018 09:56:00.755] Added shop as single chest. (#8400)

**Comment by EpicEricEE** [comment]
```
[14:05:07 INFO]: Holo Text: 5399779ns
[14:05:07 INFO]: Holo Location: 18974ns
[14:05:07 INFO]: Holo Constructor: 734869ns
[14:05:07 INFO]: Hologram Create: 6649056ns
[14:05:07 INFO]: Item Create: 317138ns
```

It's mainly the [`Shop#getHologramText()`](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/shop/Shop.java#L215) method that is taking 81% of the time it takes to create a hologram, which is at about 4-7ms (95% of the time it takes to create the whole shop). I think it's best to try to put at least the `getHologramText()` method in its own async task, if not even the whole hologram or shop creation.

**Comment by ken-kentan** [comment]
I think so.
Can you apply own suggestion?

**Comment by EpicEricEE** [comment]
```
[14:42:37 INFO]: Requirements: 440921ns
[14:42:37 INFO]: Placeholders 724327ns
[14:42:37 INFO]: Rest - Format: 1051706ns
[14:42:37 INFO]: Rest - Format: 1140552ns
[14:42:37 INFO]: Rest - Format: 579763ns
[14:42:37 INFO]: Rest: 7253817ns
```
I've gone a bit deeper: In the `getHologramText()` method, the code after filling the maps is the one taking too long. This line seems to be the culprit:
```java
String format = plugin.getHologramFormat().getFormat(i, requirements, placeholders);
```
I have now tried in [`HologramFormat#evalPlaceholder(...)`](https://github.com/EpicEricEE/ShopChest/blob/master/src/main/java/de/epiceric/shopchest/config/HologramFormat.java#L208) to not create a new `ScriptEngine` and `ScriptEngineManager` for every evaluation, but only have one defined as a field. I'm not sure if the performance has improved with that, since the time to create/add all 51 shops varies between 50ms and up to 600ms (it mostly gets lower after the first reloads). Maybe I need to add more shops for a more accurate result, but I don't have the time to manually create 1000+ shops myself.

**Comment by ken-kentan** [comment]
Ok.

[Download here](https://minecraft.kentan.jp/dev/ShopChestSampleData.zip)
* shop_world: World data
* shops.dump: shops table data (MySQL)

Please let me know when the download finish. I delete this link :)

**Comment by EpicEricEE** [comment]
Thanks, it's finished.

**Comment by EpicEricEE** [comment]
Alright, I finally got it working.

It currently takes me up to 4 seconds to load or reload all 1485 shops and it's always getting faster (until it takes about 1 second) after every time I enter `/shop reload`.
Maybe my CPU is faster, maybe there were improvements. As I don't know how you configured your hologram format, it may be possible that you have more scripts having to be executed which could make loading the holograms slightly slower.

_(btw, you have one shop selling air, which normally is not possible)_
