### ISSUE TITLE
"Not enough money" when purchasing from any shop, for any player, with any amount of money.

### ISSUE THREAD

**Issue by graysonlee123** [EpicEricEE/ShopChest#259]
Using: 
Spigot 1.14.2 093165d-cb3d14c R0.1 SNAPSHOT
Vault 1.7.2
Economy: TheNewEconomy 0.1.1.8
Permissions: LuckPerms

**Comment by EpicEricEE** [comment]
That is probably an issue regarding worlds. Apparently, your economy plugin stores a player's balance dependent on the world (e.g. `world` does not share balances with `world_nether` or `world_the_end`). As ShopChest tries to withdraw money from the world the shop and player are in, the player probably won't have enough money _in that world_. As far as I can tell, you can share balances between worlds by configuring so in the `worlds.yml` file.
I would advise you to ask the developers of TNE for more information if needed. It may even be an issue, since this also happens with the `Multiworld` setting in TNE disabled.

**Comment by EpicEricEE** [comment]
I guess he doesn't see it as an issue, so you'll have to modify the `worlds.yml` file.
