### ISSUE TITLE
ShopChest and ARM

### ISSUE THREAD

**Issue by EmnichtdaYT** [EpicEricEE/ShopChest#300]
see yourself :D 

https://drive.google.com/open?id=11AB4bV-v64388XyH0E5Q-kdTl4RDU3PD

**Comment by EpicEricEE** [comment]
Well, ShopChest can't know when a region is being reset, so I would have to add a listener for that plugin.

**Comment by EmnichtdaYT** [comment]
Nope. Just check if the Chest is still there before doing anything

**Comment by EmnichtdaYT** [comment]
You probebly have some sort of a method/function to create the armorstand and the Item above the Chest. Just Check before doing that if the Chest is still there, if it isn't just remove the shop

**Comment by EpicEricEE** [comment]
Ah yes that would make sense

**Comment by EpicEricEE** [comment]
This is probably the reason why I haven't already done that:
The whole shop updating process (i.e. showing and hiding holograms) is asynchronous. Since I can't safely get a block's type asynchronously, I'd need to create a new synchronous task every time a hologram's visibility is toggled for a player, and check for any potential concurrency issues. I don't know how big of a performance impact that would have.

**Comment by EmnichtdaYT** [comment]
I dont really care about that, can u fix it? I really nead this fixed. You could do like a second version only for me if it is too much of a preformance problem

**Comment by james090500** [comment]
> I dont really care about that, can u fix it? I really nead this fixed. You could do like a second version only for me if it is too much of a preformance problem

Even though you're being extremely rude. I assume you used the ARM Bridge plugin?

https://www.spigotmc.org/resources/advancedregionmarket-shop-bridge.77484/

**Comment by EmnichtdaYT** [comment]
Omg!!! You are amazing
