### ISSUE TITLE
High numbers in timmings

### ISSUE THREAD

**Issue by Poweringg** [EpicEricEE/ShopChest#72]
Hi, i pasted my timmings, because i had low TPS, but i saw ShopChest with big numbers, look here: 
https://timings.spigotmc.org/?url=yokipixuco

World, in wich is my shops (ca. 140shops at one place), lowering my TPS to AVG. 16TPS with 10 Players on server. 

See:
`0.05%	 939.56%	  0.47 s	   469.78 ms	 0.0	       0.0k	    Task: ShopChest$6(interval 24000)`
and
`51.89%	  65.53%	451.86 s	    32.77 ms	 1.0	      13.8k	    RedSurvivalLobby - tracker` - world with shops

**Comment by EpicEricEE** [comment]
These high values are caused by the automatic shop reloading. Since the shop creation cannot be performed asynchronously, it is blocking the main thread to perform other actions which leads to lower TPS or higher timings. However, as I don't think that this feature is needed, it is removed with commit f95122d and will no longer exist in future version (and the latest [development builds](http://epiceric.square7.de/bukkit/plugins/)).
